### PR TITLE
Cassandra 4.0 support

### PR DESCRIPTION
**Pull request by johndelcastillo**
Add support for Cassandra 4.0+ clusters

* Tested agent and standalone, locally using CCM running Cassandra 4.1.0 and Prometheus 2.42.0.

* Includes a WIP integration test framework developed by @zegelin

* Cassandra 4 changes largely inspired from [https://github.com/instaclustr/cassandra-exporter/pull/102](url)

### CODE REVIEW

**Comment by mindaugaszilionis** [comment]
Hi, nice to see some progress. When we can expect release?:)

**Comment by benbromhead** [comment]
Largely looks good to me, however I think a bunch of python cache files where checked in and should get cleaned up unless there is a good reason to have them in repo?

**Comment by johndelcastillo** [comment]
Removed the python guff, not needed.

**Comment by greut** [comment]
Thanks for the hard work! It could really have been a 0.10.0 release.

**Comment by rajesh-sapkale** [comment]
HI @johndelcastillo 
Thank you for your hardwork.
Fix is working fine for Cassandra 4.1 on Ubuntu 20, But getting following error on Ubuntu 18


`WARN  [cassandra-exporter-harvester-defer-0] 2023-05-26 11:51:37,289 Harvester.java:191 - Failed to register collector for MBean org.apache.cassandra
.metrics:type=Connection,scope=xx.xx.xx.xx_7001,name=Timeouts.
java.lang.IllegalArgumentException: 'xx.xx.xx.xx_7001' is not an IP string literal.
        at com.google.common.net.InetAddresses.formatIllegalArgumentException(InetAddresses.java:987)
        at com.google.common.net.InetAddresses.forString(InetAddresses.java:143)
        at com.zegelin.cassandra.exporter.MetadataFactory.endpointLabels(MetadataFactory.java:71)
        at com.zegelin.cassandra.exporter.FactoriesSupplier.lambda$connectionMetric$17(FactoriesSupplier.java:474)
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$withLabelMaker$0(FactoriesSupplier.java:73)
        at com.zegelin.cassandra.exporter.FactoriesSupplier$FactoryBuilder.lambda$build$1(FactoriesSupplier.java:99)
        at com.zegelin.cassandra.exporter.Harvester.lambda$registerMBean$0(Harvester.java:174)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
`

`WARN  [prometheus-netty-pool-0] 2023-05-26 11:45:49,208 DefaultChannelPipeline.java:1152 - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.nio.BufferOverflowException: null
        at java.base/java.nio.HeapByteBuffer.put(HeapByteBuffer.java:221)
        at java.base/java.nio.ByteBuffer.put(ByteBuffer.java:914)
        at com.zegelin.prometheus.exposition.NioExpositionSink.writeAscii(NioExpositionSink.java:34)
        at com.zegelin.prometheus.exposition.text.TextFormatMetricFamilyWriter$MetricVisitor.writeMetric(TextFormatMetricFamilyWriter.java:136)
        at com.zegelin.prometheus.exposition.text.TextFormatMetricFamilyWriter$MetricVisitor.lambda$visit$4(TextFormatMetricFamilyWriter.java:181)
        at com.zegelin.prometheus.exposition.text.TextFormatMetricFamilyWriter$MetricVisitor.lambda$metricWriter$0(TextFormatMetricFamilyWriter.java:
155)
        at com.zegelin.prometheus.exposition.text.TextFormatMetricFamilyWriter.writeMetric(TextFormatMetricFamilyWriter.java:227)
        at com.zegelin.prometheus.exposition.text.TextFormatExposition.nextSlice(TextFormatExposition.java:81)
        at com.zegelin.prometheus.exposition.FormattedByteChannel.read(FormattedByteChannel.java:24)
        at io.netty.handler.stream.ChunkedNioStream.readChunk(ChunkedNioStream.java:112)
        at io.netty.handler.stream.ChunkedNioStream.readChunk(ChunkedNioStream.java:31)
        at io.netty.handler.codec.http.HttpChunkedInput.readChunk(HttpChunkedInput.java:102)
        at io.netty.handler.codec.http.HttpChunkedInput.readChunk(HttpChunkedInput.java:43)`
        
Any help will be appreciated

**Pull request merged**
