### PR TITLE
Support for 4.0

### PR DESCRIPTION
**Pull request by benbromhead**
WIP and largely here for comments.
Performance is slower vs 3.11 so some changes still to be made.

Waiting on @zegelin to finish test harness so we can have some assurance on correctness.

### CODE REVIEW

**Comment by danischroeter** [comment]
Too bad this never got finished :cry:  
I liked cassandra-exporter but without this I guess I'll have to look for another monitoring source for cassandra 4. This would fix #23
Is this project dead? @zegelin

**Comment by benbromhead** [comment]
Hi @danischroeter the project is still alive however our primary maintainer has been on paternal leave :)

**Comment by danischroeter** [comment]
Hi @benbromhead 
Thanks for the speedy reply! And glad to hear.
We are currently using cassandra-exporter (and really are happy with it) but with 4.0 it no longer works... 
```
java.lang.NoSuchMethodError: 'java.net.InetAddress org.apache.cassandra.utils.FBUtilities.getBroadcastAddress()'
	at com.zegelin.cassandra.exporter.InternalMetadataFactory.localBroadcastAddress(InternalMetadataFactory.java:87)
	at com.zegelin.cassandra.exporter.Harvester.globalLabels(Harvester.java:283)
	at com.zegelin.cassandra.exporter.netty.HttpHandler.sendMetrics(HttpHandler.java:289)
	at com.zegelin.cassandra.exporter.netty.HttpHandler.channelRead0(HttpHandler.java:91)
	at com.zegelin.cassandra.exporter.netty.HttpHandler.channelRead0(HttpHandler.java:36)
```
I guess you already know since this patch seems to address this ;) 
Can we somehow finish this and merge it? I think I could also help but I don't want to invest time into something that does not get merged/used. 
( :thinking: If only a primary maintainer can create a release and is absent for multiple months I probably better invest into another project.)

**Comment by lapo-luchini** [comment]
> Performance is slower vs 3.11 so some changes still to be made.

I'd suggest to prioritize basic support (with indication in the release comments) first and target performance later. 😇

**Comment by rajesh-sapkale** [comment]
Hi @benbromhead @danischroeter, 
Cassandra exporter is awesome. Hope the compatibility issue with Cassandra 4 or the newer version gets fixed.
Any idea about the status of this project? Do we need to move to another monitoring solution?

Any help will be much appreciated.

**Comment by kenta2097** [comment]
Hi @benbromhead @bbromhead @danischroeter  @zegelin 
We are at the same point as @rajesh-sapkale and really hopeful that the exporter work will continue and be compatible with Cassandra version +4.0

The project seems to be stalled at this point, Is there any possibility to know the general status?
Or will we need to find another way to monitor Cassandra?

Any response is appreciated.

**Comment by zegelin** [comment]
I have set aside time this week and next to make progress on the support for C* 4.0.

Stay turned for updates.

**Comment by kenta2097** [comment]
We will wait for your updates.

**Comment by kenta2097** [comment]
> I have set aside time this week and next to make progress on the support for C* 4.0.
> 
> Stay turned for updates.

Hi @zegelin
We'll be happy to know if there's any update.
:)

**Comment by zegelin** [comment]
Currently on personal leave. Will be back next week with more updates.
________________________________

**Comment by mindaugaszilionis** [comment]
Will cassandra users get some present for Christmas?:)

**Comment by kenta2097** [comment]
> Currently on personal leave. Will be back next week with more updates.
> […](#)

Hi @zegelin,

I hope all is ok from your side.
There's any movement regarding the support for Cassandra 4.0?
Please let us know in case this work is stalled or if It will never be completed to find an alternative solution to gather Cassandra metrics.

**Comment by zegelin** [comment]
Hi All,

Late December I decided to move on from Instaclustr.
I'll let someone from Instaclustr comment on the future of this project going forward.

Sorry to be the bearer of potentially bad news.

**Comment by benbromhead** [comment]
Hi All, that will be me! Let me get the patch in shape and finish the handover from Adam :)

**Comment by kenta2097** [comment]
Hi @benbromhead,

What happened to close this PR?
There are plans for the support for Cassandra 4.0?

Regards

**Comment by benbromhead** [comment]
Sorry changes on my branch need reworking, will look to reopen

**Comment by johndelcastillo** [comment]
Hi all, looking at this now. It will take me a sec to come up to speed.

**Comment by johndelcastillo** [comment]
Hi all, just merged #108 into main and cut the 0.9.12 release. Any bugs or feedback should go into new issues, thanks.

**Pull request closed without merging**
